### PR TITLE
PP-5230 update confirmation page design

### PR DESCRIPTION
**Pull request by jonheslop**
- No more payment summary floating on the right, its all in tables
- Bigger clearer pay button at the top

02 confirm-your-payment

### CODE REVIEW

**Comment by alexbishop1** [comment]
Is it unchanged on mobile?

**Comment by jonheslop** [comment]
It looks like this

Screenshot_2019-05-21 Confirm your payment

**Comment by alexbishop1** [comment]
In the past, we deliberately changed the confirm page so that it had the grey summary box in the same position as the card details page. This reduced the number of people who didn’t complete their payment after reaching the confirm page. This design changes it back somewhat. Are we assuming that the more prominent confirm button will counteract the reduced visual continuity between the card details page and the confirm page?

**Comment by jonheslop** [comment]
I think we’re just gonna try it out and see how conversion changes.

The summary was moved to the bottom on mobile which sorta makes it redundant and on desktop, things aligned to the right cause issues for people using zoom text or alike.

The idea is that having the button bigger and at the top makes it clear, the journey  isn’t over and users need to click it to finish. We’re hoping it decreases the number of abandoned payments

**Pull request merged**
