### PR TITLE
PP-7216 update country list

### PR DESCRIPTION
**Pull request by gidsg**
## WHAT
Updates country list based on diff against CSV from https://data.gov.uk/dataset/0b412b57-6934-4f28-b495-640cdc7e8f7f/foreign-commonwealth-and-development-office-geographical-names-index (I wrote a [little python script](https://gist.github.com/gidsg/84e15fb65fe9eea159324369b33f2870) to compare the CSV against our current JSON.)

**Question** should we add the old names as synonyms for the new ones in the autocomplete graph?

## HOW 
Updated country names should appear in country picker on payment page e.g. North Macedonia.
Screenshot 2021-09-28 at 11 18 33

### CODE REVIEW

**Comment by alexbishop1** [comment]
> **Question** should we add the old names as synonyms for the new ones in the autocomplete graph?
Yes, I think that’s a good idea. People may have become used to typing the old names so it would be surprising if they suddenly stopped working.

**Comment by gidsg** [comment]
@alexbishop1 OK I've added a synonym for Swaziland now (the others contain their new name within the old one so will continue to work if people type the old value)

**Comment by alexbishop1** [comment]
Do we also want synonyms for Burma and Macedonia? It seems a little delicate to rely on the fact that they’re substrings of the new names.

**Comment by gidsg** [comment]
> Do we also want synonyms for Burma and Macedonia?

OK I added these now and forced pushed in 1e13ff4

**Review by alexbishop1 — APPROVED** [review]

**Pull request merged**
