### PR TITLE
BAU - use minified JS

### PR DESCRIPTION
**Pull request by jonheslop**
This should have never have been changed 🙈
I think Silvia and I were just making it easier to debug but shouldn’t
have ever shipped to production 🤦‍♂️

### CODE REVIEW

**Comment by jonheslop** [comment]
TBF I think it was almost certainly me

**Comment by jonheslop** [comment]
But happy to scapegoat @simad as she left us

**Comment by jonheslop** [comment]
Yeah nice idea

**Comment by simad** [comment]
@alexbishop1 
bye

**Pull request merged**
