### PR TITLE
BAU Release product page with fixed link

### PR DESCRIPTION
**Pull request by stephencdaly**

### CODE REVIEW

**Comment by alexbishop1** [comment]
Any idea why this changes lots of `resolved` entries in the package-lock.json from HTTPS to HTTP?

**Comment by stephencdaly** [comment]
Node rubbish, Jon's said its fine before. Would be ideal if that didn't happen but shouldn't be a problem

**Comment by alexbishop1** [comment]
According to https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/47 it’s a registry bug but any actual downloads will always use HTTPS so it’s basically just cosmetic.

**Comment by stephencdaly** [comment]
ah good to know, thanks 👍

**Pull request merged**
